### ISSUE TITLE
screengrab segfaults if file format is changed in screengrab.conf to something not valid

### ISSUE THREAD

**Issue by agaida** [lxqt/screengrab#104]
@tsujan, you might be interested in:  
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905967

(And i would bet that there are many funny surpises in the current code)

**Comment by tsujan** [comment]
I'll investigate it.

**Comment by tsujan** [comment]
Fixed here: https://github.com/lxqt/screengrab/pull/105
