### ISSUE TITLE
QCommandLineParser: option not defined: "u"

### ISSUE THREAD

**Issue by agaida** [lxqt/screengrab#115]
##### Expected Behavior
As long the upload issues are not solved "u" should be take out of the options

##### Current Behavior
At some point there is an "u" leftover

##### Possible Solution
Comment it out

**Comment by tsujan** [comment]
I'll look into the upload code soon.

**Comment by agaida** [comment]
@tsujan - Murphy strikes back again - the 'u' option should come from the upload module.

Unfortunately if i disable the upload module screengrab build and install well, but didn't start :)

**Comment by tsujan** [comment]
I didn't have a minute to take a look at the upload code ;) But who can predict the future?
