### ISSUE TITLE
Typo or not

### ISSUE THREAD

**Issue by Atalanttore** [lxqt/screengrab#135]
There's a string with text `Fill screen` in  screengrab/src/core/ui/configwidget.ui

Is that a typo for `Full screen`?

**Comment by tsujan** [comment]
Yes, it's a typo but the shortcut editor is inconvenient and should be changed -- see https://github.com/lxqt/screengrab/issues/60; I haven't had the time yet :(

**Comment by wxl** [comment]
With the merge of #136 should this not be closed?
