### ISSUE TITLE
Refactor uploader dialog's UI

### ISSUE THREAD

**Issue by paulolieuthier** [lxqt/screengrab#14]

**Comment by pmattern** [comment]
First of all I'm not sure which dialog you guys have in mind here, the one that comes up after hitting button `Upload` in ScreenGrab's main window or the one that comes up after an upload to e. g. Imgur had just been started from the former.
But while I'm not that sure whether the layout of either needs improvement in terms of usability the use of buttons `Open` and `Copy` in the latter is something that definitely should be changed, IMO.

Right now the section about the direct link features both those buttons, the extended link `Copy` only and the link to delete `Open` only
![screengrab_buttons-in-upload-gui](https://cloud.githubusercontent.com/assets/9860801/12697144/0daabd1e-c77c-11e5-9f76-090324577aeb.png)
Personally I do not think there should be a difference between these three links with regards to the two buttons and that it would hence be best if both buttons where available in all three sections.
But even if a difference shall persist it for sure does not make sense to state `Open` only next to the link to delete. This very link is the one which will most likely be needed at a later time only. So button `Copy` is definitely more important than `Open` here.

(I'm aware that copying the links is still possible by selecting them and e. g. hitting `Ctrl+C`. But if this was considered the primary means to copy button `Copy` wouldn't be needed at all.)

**Comment by agaida** [comment]
deactivated right now - must be re-implemented, bug exists.
