### ISSUE TITLE
Screen Area type doesn't have appropriate instructions

### ISSUE THREAD

**Issue by wxl** [lxqt/screengrab#161]
The instructions for a Screen Area type of shot says "Use your mouse to draw a rectangle to screenshot or exit pressing any key or using the right or middle mouse buttons." That's a horribly awkward run-on sentence, but it's also not the correct instructions.

##### Expected Behavior
Performing the steps in the instructions produces the appropriate behavior.

##### Current Behavior
 * Escape key exits entirely
 * Enter key finishes the screen shot
 * Space will toggle between two different sizes????! (sometimes)
 * Any other key does nothing
 * Right click does nothing
 * Left click does nothing
 * Middle click acts like space
 * Right double click does nothing
 * Middle double click does nothing
 * Left double click finishes the screen shot

##### Possible Solution
If we don't want to change the behavior, reword the sentence: "Click and drag with your mouse to draw a rectangle to screenshot. When finished, press enter or double click to save the screenshot. Exit the program with Escape."

##### Steps to Reproduce (for bugs)
 1. Select "Screen area" under Type
 1. Click "New"
 1. Click and drag to draw a rectangle
 1. Try to use the instructions and see what happens

##### System Information
* Distribution & Version: Lubuntu 19.10
* Kernel: 5.0.0
* Qt Version: 5.12.2
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 1.101-1ubuntu1

**Comment by tsujan** [comment]
Where are those instructions? Perhaps I have an older "Help".

It can be as simple as this: "Click and drag to draw a rectangle, then press Enter/Return or double click to take a screenshot."

**Comment by tsujan** [comment]
Never mind! It's visible in the screen-area mode. And yes, it's misleading. Would you change it?

**Comment by wxl** [comment]
Sure! Would you prefer your version or is mine sufficient?

**Comment by tsujan** [comment]
Any *concise* explanation would be good. For example, "your mouse" would be redundant ;)

Thanks in advance!

**Comment by wxl** [comment]
Oh and I guess I should file a separate issue about what space/middle mouse is doing, right? It's super weird.

**Comment by tsujan** [comment]
> Oh and I guess I should file a separate issue about what space/middle mouse is doing, right?

I'm not sure. IMHO, what you did at https://github.com/lxqt/screengrab/pull/162 will be more than enough (if you correct the problem with `Esc`) because we don't want a complete explanation in that place. Frankly, I'd never noticed the problem because drawing a rectangle and pressing `Enter` felt so natural ;)

**Comment by wxl** [comment]
I think I'll file an issue because it makes no sense to me.

Anyways, this got brought to my attention by a user on IRC and I was stumped for the same reason as you!

**Comment by wxl** [comment]
Just FYI the thing about space is actually a "[snap to border](https://github.com/lxqt/screengrab/commit/78f695f46f2dea95b221e3690d04d492dee0ec3c)" functionality. It's a little bit funky in that it works even when a rectangular area isn't present or if the background isn't ideal, which is why it seems so strange. Not sure if that's new issue worthy, so I'll put it here.

**Comment by tsujan** [comment]
> Just FYI the thing about space is actually a "snap to border" functionality

Thanks! I didn't know about it.

The option "Fit to edges only inside selected screen area" is about it. IMO, it needs a better tooltip (the current tooltip is an enigma) and the snapping shortcut should be made customizable. In this sense, it may deserve a separate report.

**Comment by wxl** [comment]
Oh you didn't know? It was in the manual…

  …the cpp one. :rofl:

It was kind of buried, too.

**Comment by tsujan** [comment]
> ... …the cpp one

:laughing: Reading the whole code is beyond my time. I just read those parts that were related to my PRs.

**Comment by wxl** [comment]
Ditto, but this one wasn't too hard to find. Got lucky this time :relieved:
