### ISSUE TITLE
Feature request: scrolling screenshot

### ISSUE THREAD

**Issue by PF4Public** [lxqt/screengrab#171]
Would it be possible to implement taking screenshots with scrolling? That is to produce a single screenshot wider and/or longer than a screen size.

**Comment by tsujan** [comment]
I'm afraid you need to be much more specific. Please make another report by filling in the template; this one isn't acceptable.

**Comment by shlyakpavel** [comment]
@tsujan instead of thousand words
https://www.youtube.com/watch?v=mCt31ALsbQA

**Comment by tsujan** [comment]
@shlyakpavel If it's about picking a window and taking its screenshot, it's already possible. But if it means picking a part of a picture, erasing the other parts, and showing the remaining as a screenshot, then, first, that isn't a *screenshot* and second, only advanced image editors might do it.

**Comment by PF4Public** [comment]
So, instead of requesting more information and allowing me to edit this information into this feature request, you're simply closing this? You're kidding me?

**Comment by shlyakpavel** [comment]
@PF4Public no one is kidding you. We just prefer to see more details in a new issue:)

**Comment by tsujan** [comment]
@PF4Public No kidding! We may close any report when the template isn't filled, *without any explanation*. In this case, I asked you to open a sensible report.

**Comment by shlyakpavel** [comment]
@tsujan on Android it is implemented in quite a different way :)
The way you've mentioned is complicated and has a lot of limitations

**Comment by tsujan** [comment]
@shlyakpavel I'm not sure but maybe the word "screenshot" has a different meaning for mobiles.

**Comment by shlyakpavel** [comment]
> @shlyakpavel I'm not sure but maybe the word "screenshot" has a different meaning for mobiles.

I'm afraid you still didn't get the idea

**Comment by shlyakpavel** [comment]
![Screenshot_20191004-231255](https://user-images.githubusercontent.com/19782228/66237024-a66fc280-e6fc-11e9-9506-dd6a476716de.jpg)

**Comment by tsujan** [comment]
> I'm afraid you still didn't get the idea

Quite possible ;) I saw the video and explained what I saw. Sometimes, a clear explanation is worth thousands of images :P

**Comment by shlyakpavel** [comment]
> > I'm afraid you still didn't get the idea
> 
> Quite possible ;) I saw the video and explained what I saw. Sometimes, a clear explanation is worth thousands of images :P

I've edited the previous message to show a screenshot we've mentioned. Hope now it is clear

**Comment by tsujan** [comment]
OK, your attached image isn't what we call a "screenshot" (as I thought). It's automatic image editing.

**Comment by shlyakpavel** [comment]
> OK, your attached image isn't what we call a "screenshot" (as I thought). It's automatic image editing.

Not really. The virtual screen is expanded in size, the program window resized and the shot taken Then everything is back. No need to edit anything

**Comment by tsujan** [comment]
So, it means taking the screenshot of an offscreen window?

**Comment by shlyakpavel** [comment]
> So, it means taking the screenshot of an offscreen window?

Practically yes

**Comment by tsujan** [comment]
OK. screengrab doesn't do that. I'm not sure if it's possible under X11 (like you mentioned above).

BTW, compare "screenshot of offscreen windows" with the first comment on this page. Some users expect telepathy from us...

**Comment by PF4Public** [comment]
@shlyakpavel well, if you're not kidding, then you're definitely wasting my (and conversely ­— your) time by not allowing me to improve this (already existing) feature request. And if you insist on filling the template, then… well, it's a pity that I live in a different reality, which doesn't allow me to _expect_ <s>The Spanish Inquisition</s>  the "expected behaviour", which I _do not expect_ until it is implemented. And I have no idea how would I have filled in the "current behaviour", which (surprise–surprise!) is lacking. 

>BTW, compare "screenshot of offscreen windows" with the first comment on this page.

BTW, haven't you by any chance compared the title of the video in the third comment with the first comment on this page? You should try, really! Lets compare everything to everything! More fun! Yay!

But anyway "offscreen windows" is a bad term here as the window itself could be very well within the screen bounds, but its content _scrollable_. Got it? I thought this is quite obvious. Oh, well, I live in different reality, fine.

>OK. screengrab doesn't do that.

Really? Wow! I wonder, how does "feature request" from the first comment on this page compare to "there is a bug". There ought to be some similarity after all…

@tsujan Thank you for your kindness and support with this issue… and friendliness and whatever. Please _do_ continue closing any reports, _without any explanation_.

This experience is astonishing and indeed an eye-opener, I'm now completely removing _this_ software from my harddrive. Never used LXQT and now I know, why I should _not_ in the future.

**Comment by shlyakpavel** [comment]
@PF4Public Firstly, I'm not from LXQt team and I see no reason you should remove lxqt for my comments. Secondly, why do you comment so toxic? After all, we both share the same goal: adding new features and improving software :)
What kind of friendliness do you expect from us? On the one hand, we were neither rude nor toxic to you. On the other hand, you haven't paid us for reading your mind and making things instantly for you.
Peace.

**Comment by tsujan** [comment]
@shlyakpavel You'll get used to it ;) BTW, you're an LXQt dev to me.

@PF4Public Please use your mind when reporting something, not your "heart"; the latter isn't our concern (here).

**Comment by agaida** [comment]
Let's not waste any time with this request - the idea is maybe good, the behaviour of the requester not. Hell, we force people to read text longer than 154 characters. Disgusting. So i will lock the discussion for now before it escalate further. 

@shlyakpavel - well, i made a mistake and didn't official invite you, you should be an official dev here. Really :D
