### ISSUE TITLE
"Edit in..." not working, tmp file doesn't exist

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/screengrab#203]
I tried to open the screenshot in Gimp, but I got:
l’ouverture de « /tmp/screenshot-def02bae.jpg » a échoué : Impossible d’ouvrir « /tmp/screenshot-def02bae.jpg » en lecture : Aucun fichier ou dossier de ce type
Indeed, there was no jpg files in /tmp.

##### Expected Behavior
Gimp open the picture.
##### Current Behavior
No picture found nor opened.
##### Steps to Reproduce (for bugs)

1. Take a screenshot
2. Choose "Edit in..." then Gimp
3. Get a message from Gimp saying that the file can't be found.

##### System Information
* Distribution & Version: Mageia 7
* Kernel: 5.4
* Qt Version: 5.12.6
* Package version: 1.101

**Comment by tsujan** [comment]
Not reproducible.
