### ISSUE TITLE
save window: tab-key does not work properly

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#213]
click on the save-button in the symbol bar: the window "Save As..."will appear
mark a document name
then press the tab-key (to switch to the File name)
normally the File name should be marked (example: LibreOffice Writer works like this)
the issue: you have to press 4x the tab-key to switch to the File name

##### System Information
* Lubuntu 20.04
* Qt Version: 5.12.8
* ScreenGrab 2.0.0

**Comment by tsujan** [comment]
This isn't related to screengrab but the file dialog: Qt's default file dialog needs only one tab. GTK file dialog needs 4 tabs. LXQt file dialog (ours) needs 3 tabs...

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/libfm-qt/issues/557 because it's good to reach the name entry by pressing tab once but the new behavior will be only for LXQt; we don't have control over other file dialogs.
