### ISSUE TITLE
Upload to Imgur account

### ISSUE THREAD

**Issue by pmattern** [lxqt/screengrab#23]
It would be quite beneficial if ScreenGrab allowed for uploading images to registered accounts with Imgur representing the only realistic option right now.

Tracking uploaded images would get much easier that way. This in turn would ease deleting images and, more importantly, posting links of images once more at a later time.

Corresponding information can be found on [api.imgur.com](http://api.imgur.com/).

**Comment by agaida** [comment]
Won't fix the current and ancient implementation.
