### ISSUE TITLE
Options-window appears at different positions in the German version of Lubuntu

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#232]
Options-window does not always appear at the same position;
this issue appears in the German-version of Lubuntu;
maybe the issue appears in other languages;
IMPORTANT: I could not reproduce the issue in the live-version of Lubuntu, so in English

##### Expected Behavior
Options-window should appear always at the same position

##### Current Behavior
Options-window does not appear always at the same position

##### Possible Solution
I have no idea

##### Steps to Reproduce (for bugs)
1. open ScreenGrab
2. click on the Options-symbol in the symbol-bar (Options-window appears in the middle)
3. in the Options-window: click on "System tray"
4. in the Options-window: deactivate "Show ScreenGrab in the system tray"
5. in the Options-window: click on "Save"
6. click on the Options-symbol in the symbol-bar (Options-window appears in the middle)
7. in the Options-window: click on "System tray"
8. in the Options-window: activate "Show ScreenGrab in the system tray"
9. in the Options-window: click on "Cancel" (!!!!)
10. click on the Options-symbol in the symbol-bar (Options-window appears top left)
11. if Options-window still appears in the middle, then click in the Options-window in the title bar on the x  to close the Options-windows; now click again on the Options-symbol in the symbol-bar (Options-window appears top left)

##### Context
Options-window should appear <b>always</b> at the same position

##### System Information
* Distribution & Version: Lubuntu (German version)
* LXQt: 0.15.0
* Qt Version: 5.14.2
* ScreenGrab: 2.0.1
* Qt: 5.14.2

**Comment by tsujan** [comment]
I can't reproduce it here, with KWin, but I know that it's possible. It isn't related to localization but to the window manager as well as the compositor. On X11, some WMs (like KWin) have a "good behavior" most of the time, some don't. Nothing can be done in the app to guarantee that all X11 WMs will always obey Qt's window positioning.

Under Wayland, the app can't determine the positions of its windows, although screengrab doesn't work under Wayland.
