### ISSUE TITLE
single-window vs multi-window: different behavior when pressing print-key many times

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#234]
multi-window: when print-key is pressed, ScreenGrab is always in foreground;
single-window: when print-key is pressed, ScreenGrab is in foreground, but only after the first screenshot

##### Expected Behavior
single-window: every time  print-key is pressed, ScreenGrab should be in foreground

##### Current Behavior
single-window: Screengrab is in foreground, but only after the first screenshot

##### Possible Solution
I think there are 3 different solutions:
1)
put in single-window after each screenshot ScreenGrab in foreground (like this works now in multi-window)
2)
in the options, in "Advanced", add a checkbox with this kind of text: "ScreenGrab in foreground after each screenshot" (just before "Allow mutiple instances of ScreenGrab"); I suggest that it should be activated by default
3)
like solution number 2, and add a sub-checkbox that will be possible to activate/deactivate  if "ScreenGrab in foreground after each screenshot" is activated with this kind of text: "only for the first screenshot"

I prefer solution number 2 because it is not so complicated than solution number 3, and it gives more freedom to the user than solution number 1;
if solution number 2 or solution number 3 will be realized, then keep in mind that those settings should affect also multi-window

##### Steps to Reproduce (for bugs)
1. open Firefox
2. press the print-key (result: Screengrab is in foreground)
3. switch back to Firefox
4. in Firefox: visit an other website
5. press again the print-key (result: Screengrab is in foreground)

now go in the options, change to single-window (click on "Advanced", deactivate the checkbox "Allow mutiple instances of ScreenGrab", and click on "Save"); then close ScreenGrab; then do again the same steps from 1 to 5; then you will see, that at step 5 ScreenGrab is not in foreground

##### Context
whether single-window or multi-window:
pressing print-key many times should have <b>always</b> the same behavior

at the moment (because I don't like multi-window) in single-window I need to close ScreenGrab always after saving, so that ScreenGrab will always appear in the foreground after each screenshot

##### System Information
* Distribution & Version: Lubuntu 20.10
* LXQt: 0.15.0
* Qt Version: 5.14.2
* ScreenGrab: 2.0.1
* Qt: 5.14.2

**Comment by stefonarch** [comment]
window(s)= instance(s)
Please use the same words as in the application.
And for "Possible solutions": you don't have to fill out this when you have no idea about the code.
 > single-window: Screengrab is in foreground, but only after the first screenshot

This is only true when "Show in system tray" **AND** "Minimize to tray when closing" is set and it's just normal.

**Comment by ralf3u** [comment]
@stefonarch 

>window(s)= instance(s);
Please use the same words as in the application.

I'm sorry; I changed title and content of this issue from "window" to" instance"

>This is only true when "Show in system tray" AND "Minimize to tray when closing" is set and it's just normal.

well, in my case both are deactivated

**Comment by ralf3u** [comment]
@stefonarch

>This is only true when "Show in system tray" AND "Minimize to tray when closing" is set and it's just normal.

I absolutely don't understand what you mean.

Both values mentioned by you ("Show in system tray" and "Minimize to tray when closing"), activated or deactivated, will bring exactly the same behavior:
ScreenGrab (in single-instance) need FIRST to be closed, so that then, when the print-key is pressed again, ScreenGrab is again in foreground

both values mentioned by you ("Show in system tray" and "Minimize to tray when closing") have no influence on the subject at all

here again the core of the subject:
whether single-instance or multi-instance:
pressing print-key a second time or many times should have always the same behavior:
ScreenGrab should be in foreground just after the print-key is pressed

**Comment by stefonarch** [comment]
I've neither  the time nor the passion to go trough this again.
On  latest code the behavior is this I described and it has its logic.
