### ISSUE TITLE
add in the options: "don't open ScreenGrab when print-key is pressed"

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#239]
What about the idea to add in the options in "Advanced" in "Autosave screenshot" a sub-checkbox like "don't open ScreenGrab when print-key is pressed" ?

I don't know how to program a software, so maybe this can not be realized;
at least I think it is a cool idea, because once the settings are done in ScreenGrab, I can make many screenshots, while ScreenGrab will not be present any more, neither as window in the taskbar, nor in the task-switcher, nor as icon in the system tray;
it would be a kind of silence-mode;
instead of 3 open windows, I would have then only 2 open windows, namely firefox and pcmanfm-qt;
pcmanfm-qt would be there to control and rename the screenshots
<br><br>
by the way, some screenshots are not possible with ScreenGrab; examples:
- let appear the main menu, then press the print-key
- click with the left button in the panel on the connections, then press the print-key
<br><br>
##### System Information
* Distribution & Version: Lubuntu 20.10
* LXQt: 0.15.0
* Qt Version: 5.14.2
* ScreenGrab: 2.0.1
* Qt: 5.14.2

**Comment by stefonarch** [comment]
>  by the way, some screenshots are not possible with ScreenGrab

by the way: not true - use delay.

**Comment by ralf3u** [comment]
@stefonarch
indeed, with a delay it is possible; thank you; I did not know that

what I just recognized, in case you are interested:  in ScreenGrab the panel (auto-hide or not-auto-hide) is half over the delay-text

Is the issue invalid because ScreenGrab in silent-mode can't be programed or because I did not respect how to fill an issue, so I should open again a new issue and respect how to fill an issue?

**Comment by tsujan** [comment]
It isn't about respecting anything. Your report was just invalid.

And never open a report again!

**Comment by ralf3u** [comment]
when panel is in auto-hide, and if ScreenGrab is maximized, and if panel is shown, "Zoom area around mouse" is not visible and not so easy to click;

it would be better to put "Zoom area around mouse" in the horizontal line of "Type" and "Delay", on the right side of "Delay";
and then "Type" and "Delay" and "Zoom area around mouse" should be centered under the screenshot

the two pictures down below show when panel is in auto-hide,
on the left when panel is not visible and on the right when panel is visible

![2021-05-06_screengrab](https://user-images.githubusercontent.com/68117017/117362702-e17b3e80-aebb-11eb-9224-97892eb76732.jpg)
