### ISSUE TITLE
saving images: setting default file type is faulty

### ISSUE THREAD

**Issue by pmattern** [lxqt/screengrab#25]
Changing the default file type at Options - Main (left pane) - Saving (tab in right pane) - Format works either faulty or not at all.

Steps to reproduce
1. Make sure no ScreenGrab instance is running, `~/.config/screengrab` in a particular user's home directory doesn't preexist and have that user launch a new desktop session.
2. Launch ScreenGrab.
3. Save the screenshot taken upon launch by hitting the disk icon without taking any other action before.
   Most of the time (see below) the file types in fields "File name" and "Files of type" in dialog "Save As..." will be consistent  
   ![screengrab_save-file-type_save-as-consistent](https://cloud.githubusercontent.com/assets/9860801/12011450/431a9a88-accd-11e5-9cdc-d3ffe2920b8b.png)  
   and saving works as expected.
4. Change the default file type at Options - Main - Saving - Format as stated above.
5. Take and save another screenshot with or without restarting ScreenGrab.
   One of two findings can be made, failed to figure out which takes place when so far
   1. The change isn't considered at all and the file types in dialog "Save As..." as shown above stay the same.
   2. The file types in the said fields "File name" and "Files of type" are inconsistent  
      ![screengrab_save-file-type_save-as-inconsistent](https://cloud.githubusercontent.com/assets/9860801/12011452/50b3eb22-accd-11e5-88c2-9e719f5a76b3.png)  
      If no further action is taken a file of the type stated in "Files of type" will be saved with a filename extension comprising both file types. E. g. here a bitmap file `screen03.png.bmp`.

Sometimes inconsistent file types as described in 5. ii. can already be seen right after starting ScreenGrab according to steps 1 and 2.
Again I failed to figure out the trigger. This finding is particularly strange as grepping for the file type in question, `*.bmp` in the example above, in the respective user's `~` didn't yield any results so far.

3b687f6 on Arch Linux i686 or x86_64.

**Comment by agaida** [comment]
Done somewhen in the ongoing refactoring

**Comment by scott092707** [comment]
"Fixed" in what version? - I have 1.97-2, in Lubuntu Next 18.04, and still have the issue
(see: https://github.com/DOOMer/screengrab/issues/82  (Yes, I know - filed in the wrong place!)).

**Comment by agaida** [comment]
Fixed in git - thats how software development works. We will release screengrab somewhen in near future - and somewhen it will hit the distributions.
