### ISSUE TITLE
the window is not maximized any more after clicking twice on the ScreenGrab-icon in the systemtray

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#266]
##### Steps to Reproduce (for bugs)
1: open ScreenGrab from the application menu; the window should be maximized (if it is not maximized: maximize the window)
2: click 2 times on the ScreenGrab-icon in the system-tray (to let disappear the ScreenGrab-window and to show again the ScreenGrab-window)

##### Current Behavior
the window is not maximized

2 possibilities to see this:
1: click the maximize-icon to see the difference
2: right click in the panel in the Task Manager on the ScreenGrab-icon of the open window: maximize can be selected

##### Expected Behavior
the window should be maximized
##### System Information
* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* SreenGrab 2.1.0

my ScreenGrab 2.1.0 is old; but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.2.0 any more, then I’m sorry for this report

**Comment by stefonarch** [comment]
Confirmed, but I would not consider this an issue - a screen capture program is hardly ever used maximized.
Any other window size is always remembered.

**Comment by ralf3u** [comment]
I always use it maximized

**Comment by tsujan** [comment]
@stefonarch
I may have not understood this, especially because there's no double click action for the tray icon.

However, here, if I click the tray icon when the window is maximized, the window will hide and if I click it again, it'll reappear maximized. As you may know, I use KWin.

**Comment by stefonarch** [comment]
So it's a WM thing - with openbox only the window size is remembered and not maximize, no idea with xfwm4 but @ralf3u uses ubuntu/openbox I assume.

**Comment by tsujan** [comment]
I have `BorderlessMaximizedWindows=true` in kwin's config file but I'll test without it and also check the code later.

**Comment by tsujan** [comment]
Follow https://github.com/lxqt/screengrab/issues/271.
