### ISSUE TITLE
the delete of the ScreenGrab-icon in the systemtray should be executed ONLY through the panel

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#267]
it happened to me already many times that I pressed the Quit-button inside the window of ScreenGrab to close ScreenGrab, and then I realized that the ScreenGrab-icon disappeared from the systemtray, although I did not want to let it disappear

the Quit-button (on top right under the minimize/maximize/close-buttons) in the ScreenGrab-window is misleading, because it does not mean at the same time to let disappear the ScreenGrab-icon from the systemtray

so the delete of the ScreenGrab-icon in the systemtray should be executed **ONLY** and **ONLY** through the panel

in Qlipper for example there is no quit-button inside the configuration-window of Qlipper;
and in Qlipper there is no shortcut to delete the Qlipper-icon from the systemtray

so, this should be realized:
- no Quit-button inside the window of ScreenGrab (on top right under the minimize/maximize/close-buttons),
- no shortcut to quit ScreenGrab, and 
- no "Quit"-entry in the Options in Shortcuts

if someone wants to close ScreenGrab with a shortcut: the shortcut to close a window is defined in openbox and can be changed there

##### System Information

* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* ScreenGrab: 2.1.0

my ScreenGrab 2.1.0 is old; but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.2.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
Quit means quit; it isn't misleading. No app "quits to system tray;" apps may *close* to systray.

**Comment by tsujan** [comment]
@ralf3u 
Although your reports are appreciated, please don't mistake your personal habits for what should or should not be in apps. This wan't the first time.

**Comment by ralf3u** [comment]
a good software should be minimalistic without losing its functionality; with the absence of the Quit-button in the toolbar, ScreenGrab would not lose its functionality at all; it would make the software even more minimalistic and even more intuitive, because the delete of an icon in the systemtray should be executed only through the panel; in Firefox, one could observe in the last years a reduction of buttons in the toolbar, to put the focus on the core tasks, and that's good; ScreenGrab should follow this path by deleting the Quit-button in the toolbar; my report #268 is the proof of pursuing a clear strategy that the delete of a systemtray-icon should be executed only from the panel; till today nobody requested inside the configuration-window of Qlipper a Quit-button, because it is not the right place where it belongs; the right place of a Quit-button is in the panel, inside the context-menu of an icon in the systemtray, and nowhere else

**Comment by ralf3u** [comment]
I would like to correct this report:
<br>

in my comment above (https://github.com/lxqt/screengrab/issues/267#issuecomment-880725365), I wrote:
> my report #268 is the proof of pursuing a clear strategy that the delete of a systemtray-icon  [...]

meanwhile #268 was closed with this argument:
> This was rather like a personal note, not a report.

after #268 was closed, I recognized that it is indeed to value #268 as a personal note; I did a mistake and I want to apologize for that

nethertheless I still like the attitude of the title of this report (#267) and I still like the position of my comment above (https://github.com/lxqt/screengrab/issues/267#issuecomment-880725365), even if the proof there is wrong

so I restarded thinking; and I found a solution; here it is:

the Esc-shortcut can be deleted in the Options in Shortcuts (see description in my report #269), so what is only missing is the remove of the Quit-button in the toolbar to make the title of this report come true; it could be realized with a checkbox with something like "no Quit-button in the toolbar" in the Options in Advanced

it would be **THE perfect solution** for all, for people who agree with the title of this report, and others who don't

for an ideal ScreenGrab read also my report #272, that has some connection with this report (in report #272 it is roughly about to have ScreenGrab in the systemtray after every reboot, while this report #267 gives some kind of guarantee that it will not be deleted by mistake, nor by pressing the Esc-key nor by clicking on the Quit-button in the toolbar, so to have it **from the start permanently** in the systemtray

**Comment by ralf3u** [comment]
so, here the solution:

the Esc-shortcut can be deleted in the Options in Shortcuts (see description in my report #269), so what is missing is removing the Quit-button from the toolbar to make the title of this report come true; it could be realized with a checkbox with something like "no Quit-button in the toolbar" in the Options in Advanced

it would be **THE perfect solution** for all, for people who agree with the title of this report, and others who don't

for an ideal ScreenGrab read also my report #272, that has some connection with this report (in report #272 it is roughly about to have ScreenGrab in the systemtray after every reboot, while this report #267 gives some kind of guarantee that it will not be deleted by mistake, nor by pressing the Esc-key nor by clicking on the Quit-button in the toolbar, so to have it **from the start PERMANENTLY** in the systemtray
