### ISSUE TITLE
Esc is in general reserved to cancel a process

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#268]
##### Steps to Reproduce EXAMPLE 1
1: ScreenGrab is open and maximized; ScreenGrab-icon is in the systemtray
2: select "Screen area"
3: press Ctrl+n
4: now suddenly you realize that "Window" with "Include mouse pointer" would be better than "Screen area", so press Esc to cancel the record-process (and not to quit ScreenGrab)

##### Current Behavior
there is no ScreenGrab-icon in the systemtray any more & there is no ScreenGrab-window any more

##### Expected Behavior
the ScreenGrab-icon should be still in the systemtray and the ScreenGrab-window should appear, so you can restart the record-process but this time with "Window" with "Include mouse pointer"
<br><br>
##### Steps to Reproduce EXAMPLE 2
1: ScreenGrab is open and maximized; no ScreenGrab-icon in the systemtray
2: select "Screen area"
3: close the ScreenGrab-window
4: open ScreenGrab from the application menu to verify some settings in ScreenGrab
5: press Esc to cancel the record process (and not to stop the opening of ScreenGrab)

##### Current Behavior
there is no ScreenGrab-window

##### Expected Behavior
ScreenGrab-window should appear
<br><br>
##### Context
Esc is in general reserved to cancel a process or sometimes to close a window; a shortcut should have only one behavior and not different behaviors at the same time; Esc has at the moment 3 different behaviors at the same time in ScreenGrab:
1: if there is a record-process: cancel the record-process
2: if a ScreenGrab-window is open: close the window ScreenGrab
3: if ScreenGrab-icon is in the systemtray: delete the ScreenGrab-icon from the systemtray

even Ctrl+W / Ctrl+Q is not a good idea as shortcut for Quit (mentioned in #41) because those keys are in general to close a window/tab and not AT THE SAME TIME to do 3 things; if someone wants to close ScreenGrab with a shortcut: the shortcut to close a window is defined in openbox and can be changed there; in Qlipper for example there is no shortcut to let disappear Qlipper from the systemtray, because there is no need for that; evidence: till today nobody requested a shortcut to let disappear the Qlipper-icon from the systemtray

##### Possible Solution
#267

##### System Information
* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* ScreenGrab: 2.1.0

my ScreenGrab 2.1.0 is old; but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.2.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
This was rather like a personal note, not a report.

Didn't see an abnormal behavior.
