### ISSUE TITLE
the window is not maximized any more after pressing Esc

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#269]
##### Steps to Reproduce
1: delete the Esc-shortcut in the Options in Shortcuts
2: do example 1 and do example 2 of my report #268

##### Current Behavior
in both examples: the window is not maximized any more

##### Expected Behavior
the window should be still maximized

##### Remark
if someone is interested how I deleted the Esc-shortcut: in the Options, in Shortcuts, double-click on Esc; press the Windows-key, then press enter, then click on Save; then restart the Options; result: the Esc-shortcut has disappeared;
it could be that there will be a proper solution to delete a shortcut when #60 will be fixed (in FeatherPad for example a shortcut can be deleted with the backspace-key)

##### System Information
* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* ScreenGrab: 2.1.0

my ScreenGrab 2.1.0 is old; but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.2.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
→ https://github.com/lxqt/screengrab/issues/268

I don't know it's about the English or something else but devs shouldn't need to decipher a report; the reporter should make his point clear.
