### ISSUE TITLE
UI: small window size triggers overlapping of image preview and controls

### ISSUE THREAD

**Issue by pmattern** [lxqt/screengrab#27]
If the main window's vertical size gets decreased below some threshold the preview pane at the window's centre doesn't get adapted any longer and the controls below start overlapping.
![screengrab_preview-control-overlap](https://cloud.githubusercontent.com/assets/9860801/13268003/5ab4c7f0-da80-11e5-9fa5-0cf8050d690a.png)

This looks a bit odd, a mandatory reason for the behaviour doesn't seem to exist.
Fixing should somewhat improve the UX, in particular as the window size is below that threshold when screengrab gets launched the first time on a distinct user profile and changes by manual adjustment only (it does not get adjusted by taking screenshots of any arbitrary size).

Seen running a276ddc on Arch Linux x86_64 and i686.

**Comment by agaida** [comment]
Done in the latest refactoring
