### ISSUE TITLE
in the Options: "ScreenGrab in the systemtray after every reboot"

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#272]
##### Steps to Reproduce
1: in the Options in Advanced: activate "Autosave screenshot"
2: in the Options in Advanced: activate "Save first screenshot"
3: click on Save
4: close ScreenGrab

##### Current Behavior
now every time the Print-key is pressed, a screenshot will be automatically recorded (that's cool!)

##### Problem
if after a reboot one just want to open ScreenGrab to change the settings, is it by a shortcut, from the quicklaunch bar or from the application menu, a screenshot will be made automatically, but from ScreenGrab in the systemtray, no screenshot will be made; so, better would be to have the ScreenGrab after every reboot automatically in the systemtray to change from there the settings without losing the possibility to press the Print-Key at any time to have right away a screenshot

##### Possible Solution
- in the Options in System Tray: checkbox with something like "ScreenGrab in the system tray after every reboot"
- or: ScreenGrab as Widget in the panel, like the "Color picker"

##### System Information
* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* ScreenGrab: 2.1.0

my ScreenGrab 2.1.0 is old; but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.2.0 any more, then I’m sorry for this report

**Comment by stefonarch** [comment]
This is true when not "screen area" is selected but "window" or "desktop".
The settings are clear, and personally I save screenshots in /tmp

I don't think an option "start minimized to tray" is really needed - changing settings isn't something users do often.

**Comment by ralf3u** [comment]
@stefonarch 
> changing settings isn't something users do often

well, I do

**Comment by stefonarch** [comment]
I think you're exception, _settings_ come from _sit_ I think, not moving ;)

Thinking about it wouldn't be that easy anyway to implement, because also "start mimimized to tray" is still "start" and would produce  a screenshot anyway.

**Comment by ralf3u** [comment]
@stefonarch 

> [...] because also "start mimimized to tray" is still "start" and would produce a screenshot anyway.

I have a solution for that: in the Options in Advanced: do not activate "Save first screenshot";
et voilà, and then "start minimized to tray" would be the perfect setting, which will solve all problems of this report

**Comment by stefonarch** [comment]
> I have a solution for that: in the Options in Advanced: do not activate "Save first screenshot";
> then "start minimized to systemtray" would be the perfect setting, which will solve all problems of this report

If you don't save the first screenshot there is no problem at all anymore to access settings without doing a screenshot.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/screengrab/issues/267#issuecomment-879261955

**Comment by ralf3u** [comment]
@stefonarch 
>If you don't save the first screenshot there is no problem at all anymore to access settings without doing a screenshot.

I know this already and this was not the subject of the report; in the report there is this text:
"so, better would be to have the ScreenGrab after every reboot automatically in the systemtray to change from there the settings without losing the possibility **to press the Print-Key at any time to have right away a screenshot**"

**Comment by ralf3u** [comment]
@tsujan 

in this report I don't write what the software should do; I even don't use the word "should"; in this report I just show what does not work perfect, and I give a possible solution what would make the software even better for a strong ScreenGrab-user like me
