### ISSUE TITLE
Problem with single-instance external apps

### ISSUE THREAD

**Issue by tsujan** [lxqt/screengrab#297]
If the external app that Screengrab calls (through its "Edit in..." menu) has a single instance (like GIMP or lximage-qt) and the app has been running before being called by Screengrab, then the temporary file will immediately be deleted and the app could not open it.

For example:

 1. Start lximage-qt/GIMP.
 2. Start Screengrab and call lximage-qt/GIMP through Screengrab's menu.

**Comment by stefonarch** [comment]
It's _you_ who find hidden bugs ;)
Fun fact: if some image files in /tmp exist it will open just the last one alphabetically and not show any error message.

**Comment by tsujan** [comment]
> It's you who find hidden bugs ;)

I started with your report (https://github.com/lxqt/screengrab/issues/294) and was frightened by what I saw ;)
