### ISSUE TITLE
does not respect `mimeapps.list`, suggests chromium and gpicview

### ISSUE THREAD

**Issue by arctic-penguin** [lxqt/screengrab#302]
##### Expected Behavior
After taking a screenshot and clicking `Edit in ...`, I expect to see only the apps that I have specified under `$XDG_CONFIG_HOME/mimeapps.list` for the filetype `image/png`.

##### Current Behavior
After clicking `Edit in ...`, I see all apps that I have listed in `mimeapps.list`, but also chromium and gpicview, which I did not put there.

##### Possible Solution
I would assume `mimeapps.list` is never checked.

##### Steps to Reproduce (for bugs)
1. Install these programs: feh, gpicview, gimp, inkscape, chromium 
2. Put the `mimeapps.list` from below under `$XDG_CONFIG_HOME/mimeapps.list`
3. Take a screenshot with screengrab
4. Click `Edit in ...`

`mimeapps.list`:
```
[Default Applications]
image/png=feh.desktop

[Added Associations]
image/png=org.inkscape.Inkscape.desktop;feh.desktop;gimp.desktop;
```

##### Context
AFAIK, the  XDG MIME Applications specification is the canonical method to let the user specify which app he wants to associate with certain filetypes. I would expect screengrab to respect the entries for png files.

##### System Information

* Distribution & Version:  Arch Linux, latest
* Kernel: 5.17.7
* Qt Version: 6.3.0
* libqtxdg Version: 3.9.1
* lxqt-build-tools Version: not installed 
* Package version: 2.4.0

**Comment by tsujan** [comment]
That's not how app association works. By setting the default app, you just set the app that opens the mimetype in question by default. If you don't want to see an app that handles the mimetype, you should add it to `[Removed Associations]`.

**Comment by arctic-penguin** [comment]
Understood. Thank you for the quick reply!

**Comment by tsujan** [comment]
BTW, if you want to open the image with the default app, you could just double click inside it; you don't need `Edit in ...` for that.

**Comment by stefonarch** [comment]
> If you don't want to see an app that handles the mimetype, you should add it to `[Removed Associations]`.

Interesting . seeing chromium in a menu for modifying screenshots always disturbed me somehow, nice!

**Comment by tsujan** [comment]
For now, it needs to be done manually. We should implement association removal in `lxqt-config`.

**Comment by stefonarch** [comment]
> We should implement association removal in `lxqt-config`.

Doesn't sound easy to implement. It would need listening all applications associated with `<filetype>` no?

**Comment by tsujan** [comment]
The needed method seems to exit in `libqtxdg`, but the current GUI of File Associations can't handle it.

Actually, the GUI of File Associations can't add associations without setting default apps either. I mean, you may want to be able to open `image/png` with Firefox without making Firefox the default app for `image/png`. Of course, you can do it the hard way, by first making Firefox the default app for `image/png` and then switching to the previous default app.

If we decide that these advanced jobs need a section inside File Associations, we should to discuss it somewhere. We might also think of them as too advanced and leave them to advanced users.
