### ISSUE TITLE
Screenshot of offscreen windows without including their decorations

### ISSUE THREAD

**Issue by tsujan** [lxqt/screengrab#307]
I've tested this only under KWin. Please test it under another compositor (or without compositor)!

When a part of a window is outside the screen and Screengrab takes its screenshot without including its decoration, this happens with styles that don't support translucency (the screenshot is taken with Fusion, but Breeze and *non-translucent* Kvantum themes give the same result):

![fusion](https://user-images.githubusercontent.com/981076/176988212-66f4c329-60ae-45f1-a4f8-333d60579119.png)

The screenshot will be OK with translucent themes (this one is taken with Kvantum, but QtCurve translucent themes are OK too):

![kvantum](https://user-images.githubusercontent.com/981076/176988238-cefbc997-41b8-482a-a309-b970a85d421c.png)

A similar problem existed with all styles when the screenshot *included* the decoration, but a workaround was added.

If the current problem isn't specific to KWin, it should be a Qt bug and a similar workaround could be added.

**Comment by tsujan** [comment]
OK, [Qt doc](https://doc-snapshots.qt.io/qt6-dev/qscreen.html#grabWindow) warns about it, "Warning: In general, grabbing an area outside the screen is not safe. This depends on the underlying window system."

Therefore, even if it works with some WMs/compositors, the offscreen part should be excluded.

**Comment by stefonarch** [comment]
I couldn't repeat your first screen, I get always the window completely. (kwin, fusion)

**Comment by tsujan** [comment]
Are you sure that "No window decoration" *is* checked? If yes, it may even depend on deeper graphical factors (like graphics driver).

Before I saw Qt's warning, I wasn't sure; now I think we should exclude the offscreen part.

**Comment by stefonarch** [comment]
> Are you sure that "No window decoration" _is_ checked? If yes, it may even depend on deeper graphical factors (like graphics driver).

Yes,  it was checked. Driver amdgpu. Will check on the other PC.

**Comment by tsujan** [comment]
> Yes, it was checked.

Strange! Here, lximage-qt's screenshot utility gives the same result, with or without decoration.

**Comment by tsujan** [comment]
A screenshot that shows the offscreen part can be a mess, not just black:

![featherpad](https://user-images.githubusercontent.com/981076/176996893-be88932a-1d69-462c-8650-cb6bd374ad5c.png)

**Comment by stefonarch** [comment]
I'm still not able to get one of those, neither in VM with Lubuntu/openbox and the main PC with debian/intel/kwin.

I think it's rather uncommon to make screenshots of half visible windows, but  if it works in most cases why ruin it? Maybe more tests bu others are needed.

**Comment by tsujan** [comment]
> I'm still not able to get one of those, neither in VM with Lubuntu/openbox and the main PC with debian/intel/kwin.

Here, I can't reproduce it with GTK3 windows, but Tk/Tcl and Java windows cause exactly the same problem. I think it's related to how Qt draws windows. Why it doesn't happen with translucency, I have no idea!

> but if it works in most cases why ruin it?

It makes perfect sense. Thanks! Closing...

**Comment by stefonarch** [comment]
> Here, I can't reproduce it with GTK3 windows,

I can now :) Did test with thunderbird and telegram, testing with featherpad I can reproduce it...

**Comment by tsujan** [comment]
> I can now :)

Good.

The workaround is simple, but I agree with your last argument (".... why ruin it?").
