### ISSUE TITLE
Fedora 37 dnf install screengrab not available

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [lxqt/screengrab#327]
https://github.com/lxqt/screengrab#binary-packages  
Says "Official binary packages are available in all major distributions. Just use the distributions' package manager to search for string 'screengrab'." but there isn't a package contain information about `screenbrab`

##### Expected Behavior

`dnf install screengrab`, press `PrtSc|SysRq` key, `screengrab -f`

##### Current Behavior

screengrab is not installed with `group install "LXQt"` and not available in dnf source

##### Possible Solution

Build from source
```
sudo dnf install cmake
sudo dnf install qt5-qtbase-devel
sudo dnf install qt5-linguist
sudo dnf install qt5-qtx11extras-devel
sudo dnf install kf5-kwindowsystem-devel
sudo dnf install libqtxdg-devel
sudo dnf install glib2-devel
// unpack 2.4.0 tar
// cd into unpacked dir
mkdir build
cd build
cmake ../
make
sudo make install
```
Use release 2.4.0, or package version will conflict
##### Steps to Reproduce (for bugs)

1. Install Fedora LXQT spins https://spins.fedoraproject.org/en/lxqt
2. Discover no response on PrtSc
3. Run screengrab -f and find command not found
4. Try install using dnf but no luck

##### Context

Connect remote control use XRDP, I want to press screenshot key on keyboard and paste to Windows mspaint tool.

##### System Information

* Distribution & Version: Fedora 37
* Kernel: `Linux <hostname> 6.1.13-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Qt Version: 5.15.8
* libqtxdg Version: 3.9.0
* lxqt-build-tools Version: 0.11.0
* Package version: None

**Comment by stefonarch** [comment]
If Fedora doesn't have a package for ask there please. Packaging is not our job.

**Comment by mhtvsSFrpHdE** [comment]
First day to Linux world, sorry, I'm then going to look for something like "fedora packaging forum"...

**Comment by stefonarch** [comment]
Here you can see the versions, looks like Fedora doesn't ship it anymore:
https://repology.org/project/screengrab/versions
