### ISSUE TITLE
No date-based filename suggestion when saving screenshot

### ISSUE THREAD

**Issue by normal-max** [lxqt/screengrab#374]
When you save screenshot, program does not suggests name based on date and time.

Screengrab v 2.6.0

Press screenshot
Press icon to save file
Suggested name is screen.png

This requires additional steps from user to choose and enter name for screenshot.
It is better to suggest file name based on date and time.
Like 2024-10-08_15-20-123445.png

Selecting custom name should be optional for user if he wants so, but not obligatory. Auto generated names make process easy help from accidental overwriting and are already standard for many screenshot programs.

**Comment by tsujan** [comment]
Options → Advanced → Inset current date…

**Comment by normal-max** [comment]
If this option exists. Why it is not active by default?
