### ISSUE TITLE
Delay input box remains focused after screenshot

### ISSUE THREAD

**Issue by jleclanche** [lxqt/screengrab#40]
Reproduce:

1. Change the delay by clicking the spinner
2. Take a screenshot

After the screenshot has been taken, the delay box is still focused, which causes Ctrl+C to fail to copy the screenshot (and instead copies the delay).

Additionally, ctrl+c should probably never pick up the delay box anyway, even if it is focused.

**Comment by tsujan** [comment]
> ctrl+c should probably never pick up the delay box anyway,

That's the default behavior of any line-edit -- in this special case, inside the spin-box.
