### ISSUE TITLE
"Previous selection" doesn't work logically

### ISSUE THREAD

**Issue by tsujan** [lxqt/screengrab#49]
It's in Options → Main → Screenshot → Type. If "Previous selection" means the previous choice of the user (Full screen, Window,...), it isn't respected. If it was supposed to have a different meaning, "Previous selection" couldn't be a clear way of showing that.

Since the main GUI settings are temporary (by design?), I think it should mean that the Type setting should be restored with the next session (which isn't the case). If so, the question arises as to why only this main GUI setting should be restored?

My suggestion:

*Either* remove that item and add a checkbox somewhere for restoring all the choices made in the main GUI with the next session...

... *Or* always save/restore the main GUI choices on quitting.

Ideas?

**Comment by agaida** [comment]
saving all setting would be required if one want the "previous" thing work right - but lets start with cleaning up the configuration read/write

**Comment by agaida** [comment]
up to you

**Comment by tsujan** [comment]
> up to you

OK. We could change it later if people don't agree.

More specifically, this is the main window (after some cleanup):

![main](https://user-images.githubusercontent.com/981076/38771850-bd97d0a2-403f-11e8-9b19-24184777f086.png)

And this is the Options dialog (after some cleanup, again):

![dialog](https://user-images.githubusercontent.com/981076/38771854-d229964a-403f-11e8-9c73-52485e00f09e.png)

My plan is to remove that Options tab altogether and add the remaining one option to the main window only with the selection mode. Spectacle also saves user choices in its main GUI.

**Comment by agaida** [comment]
ok, only if i understand you right - if you find another place for the advanced settings etc

**Comment by tsujan** [comment]
Only the screenshot settings should be in the main window, IMO -- because the user might need to change them constantly -- and they should be saved/restored. Other settings belong to the Options dialog.

All this may take time. I'll make a single PR for them (distro settings included). The current GUI is really strange to me (RTL layout, a redundant widget, lack of grid...).

**Comment by tsujan** [comment]
Oh, "Previous selection" means "Last selected area"! I'll change its name and add saving/restoring for it because it's useful.

**Comment by tsujan** [comment]
This is fixed now. Closing.
