### ISSUE TITLE
With systray icon, iconify the window on closing

### ISSUE THREAD

**Issue by tsujan** [lxqt/screengrab#58]
Otherwise, why having a systray icon?

**Comment by agaida** [comment]
Without globalkeys try to make a screenshot if screengrab is not selected :P With the tray ison one can do it via mouse and tray icon.

**Comment by tsujan** [comment]
> With the tray ison one can do it via mouse and tray icon.

I don't think so. A tray icon alone can't guarantee that app's shortcuts work; its window should be focused, as far as I remember.

However, I think the tray icon is useful when the user wants to take several screenshots, in which case the window should be iconified when closed.

**Comment by tsujan** [comment]
Oh, you meant mouse+tray. Why I misread your comments so much? ;) My bad!

**Comment by agaida** [comment]
In general yes - let's do this, i don't see any negative impact.

**Comment by tsujan** [comment]
If people get insulted by it, an option could be added for it later ;)

**Comment by agaida** [comment]
hmm - there is an option right now, so why change? And please think of other use cases - screengrab should replace the screenshot funtionality in lximage-qt - so it might be useful to have a screengrab icon, but not closing into it.

Additional these options should be cli-options too - a possible embedding in lximage-qt could be
exec(screengrab --with-tray-icon --close-to-tray=false)

**Comment by tsujan** [comment]
OK, I don't touch it -- just thought that option was redundant.

Actually, I think a systray icon should be always alongside "closing to systray" and hard-coded by Qt; those who don't want it could subclass... Anyhow, nothing important.

**Comment by tsujan** [comment]
I found at least 4 serious bugs in the tray icon; will fix them in a commit for About dialog because some of them are related to it.

**Comment by agaida** [comment]
and i will write a bug about scriptable/flexible uploads

**Comment by tsujan** [comment]
Sorry for ranting but I need to: For each bug I fix in the tray icon, I find yet another one -- and all them are serious. This is the buggiest tray icon I have ever seen! Tomorrow, I'll make it right.

But just for fun:
(1) Don't allow multiple instances by unchecking the related option in the Options dialog and save. Also enable the tray icon.
(2) Run the app with tray icon.
(3) Iconify the window.
(4) Show the Options dialog only from the tray context menu.
(5) Disable the tray in the Options dialog and save.
Then screengrab will disappear without exiting.

OK, you kill its process but the next time, it exits immediately and you should run it again. That's yet another bug related to a bad single-instance code -- to be fixed in another time.
